spring.application.name=Pokedex
spring.application.version=1.6.2

skaro.pokeapi.baseUri=https://pokeapi.co/api/v2/
skaro.pokeapi.maxBytesToBuffer=5065000

spring.web.resources.static-locations=classpath:/images/,classpath:/resources/
spring.web.resources.cache.period=0
#server.port=4201
server.servlet.context-path=/
spring.profiles.active=production

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Disable pointless JAR scanning noise
#server.tomcat.additional-tld-skip-patterns=*.jar
# Skip known non-TLD jars only
server.tomcat.additional-tld-skip-patterns=\
spring-*.jar,\
log4j-*.jar,\
jackson-*.jar,\
slf4j-*.jar,\
hibernate-*.jar

# Springdocs Swagger/OpenAPI configuration
springdoc.swagger-ui.config-url=/springboot/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/springboot/v3/api-docs
#springdoc.swagger-ui.config-url=${server.servlet.context-path}/${springdoc.api-docs.path}/swagger-config
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.showExtensions=true
springdoc.swagger-ui.displayRequestDuration=true

# Logging configuration found in log4j2.properties
