
skaro.pokeapi.baseUri=http://localhost:4204/pokedexapi/
skaro.pokeapi.maxBytesToBuffer=5065000

server.port=4201
server.servlet.context-path=/springboot

springdoc.swagger-ui.config-url=/springboot/v3/api-docs
springdoc.swagger-ui.url=/springboot/v3/api-docs
