name=PropertiesConfig
property.folderName=${sys:catalina.base:-.}/logs
property.fileName=PokedexLogs

property.pattern=%highlight{%-6level} %d{MM-dd-yyyy hh:mm:ss.SSS a} [%c:%M:%L] - %msg%n
property.patternPlain=%n%-6level %d{MM-dd-yyyy hh:mm:ss.SSS a} [%c:%M:%L] - %msg

# Appender denotes the destination of log output
appenders=console, rolling

appender.console.type=Console
appender.console.name=Console
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=${pattern}
appender.console.filter.threshold.type=ThresholdFilter
appender.console.filter.threshold.level=INFO

appender.rolling.type=RollingFile
appender.rolling.name=RollingFile
appender.rolling.fileName=${folderName}/${fileName}.log
appender.rolling.filePattern=${folderName}/${fileName}-%i.log
appender.rolling.layout.type=PatternLayout
appender.rolling.layout.pattern=${patternPlain}
appender.rolling.layout.footer=%n----------
appender.rolling.filter.threshold.type=ThresholdFilter
appender.rolling.filter.threshold.level=DEBUG
appender.rolling.policies.type=Policies
appender.rolling.policies.size.type=SizeBasedTriggeringPolicy
appender.rolling.policies.size.size=1GB
appender.rolling.strategy.type=DefaultRolloverStrategy
#When the the fileIndex attribute is set to "max" the following actions will be performed.
#During the max(20) rollover foo.log is renamed to foo1.log. A new foo.log file is created and starts being written to.
appender.rolling.strategy.max=20
appender.rolling.strategy.action.type=Delete
appender.rolling.strategy.action.basepath=${folderName}
appender.rolling.strategy.action.maxdepth=2
appender.rolling.strategy.action.condition.type=IfLastModified
appender.rolling.strategy.action.condition.age=30D

# Logger config for the specific class
loggers=jdkInternalHttpclientDebug, jdkInternalHttpclient, pokemonapiservice

logger.pokemonapiservice.name=pokedexapi.service.PokemonApiService
logger.pokemonapiservice.level=ERROR
logger.pokemonapiservice.additivity=true
# with additivity true, logs will be handled by:
# Any appenders configured for this specific logger
# The root logger's appenders (console and rolling file)
# If you set it to false, you'd need to explicitly configure
# appenders for this logger, or its logs wouldn't go anywhere.

# Set the logging level for the HTTP client to INFO
logger.jdkInternalHttpclientDebug.name=jdk.internal.httpclient.debug
logger.jdkInternalHttpclientDebug.level=ERROR
logger.jdkInternalHttpclientDebug.additivity=false
logger.jdkInternalHttpclientDebug.appenderRef.console.ref=Console

logger.jdkInternalHttpclient.name=jdk.internal.httpclient
logger.jdkInternalHttpclient.level=ERROR
logger.jdkInternalHttpclient.additivity=false
logger.jdkInternalHttpclient.appenderRef.console.ref=Console

# OFF > FATAL > ERROR > WARN > INFO > DEBUG > TRACE > ALL
rootLogger.level=${sys:logLevel:-all}
rootLogger.appenderRefs=Console, RollingFile
rootLogger.appenderRef.console.ref=Console
rootLogger.appenderRef.rolling.ref=RollingFile